### ISSUE TITLE
How to convert the mesh into a virtual actor

### ISSUE THREAD

**Issue by wpf-coder** [xuxy09/SMPLer#4]
This work is very meaningful, and your demo video looks very good. I would like to know what method or tool you use to transform the deduced mesh into virtual human animation in your YouTube demo video? Thank you for your answer!
![SMPLER](https://github.com/xuxy09/SMPLer/assets/72534569/ebf32dd5-7381-48f9-8594-26648f0333c5)

**Comment by HeadReaper-hc** [comment]
@wpf-coder Hi, do you know how to do it now?

**Comment by wpf-coder** [comment]
Sorry, I don't know yet

**Comment by xuxy09** [comment]
> This work is very meaningful, and your demo video looks very good. I would like to know what method or tool you use to transform the deduced mesh into virtual human animation in your YouTube demo video? Thank you for your answer! ![SMPLER](https://private-user-images.githubusercontent.com/72534569/344943922-ebf32dd5-7381-48f9-8594-26648f0333c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTQyNTEsIm5iZiI6MTcyMDE1Mzk1MSwicGF0aCI6Ii83MjUzNDU2OS8zNDQ5NDM5MjItZWJmMzJkZDUtNzM4MS00OGY5LTg1OTQtMjY2NDhmMDMzM2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA0MzIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YjVhNDI1Y2Q5ZjUwMjdkMDdjNTgzNjUwZDc3OWFhN2M5ODJhNGM3YzViNGQ0NTQ0YTc0ZTQ5NjBhMzc3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-zZ1Aq3zhAQd51fXnPkq0gSIMgI5Ku3w2xc7pmx3ANg)

You can try this: https://github.com/softcat477/SMPL-to-FBX/tree/main?tab=readme-ov-file

**Comment by wpf-coder** [comment]
Thank you so much！
