### ISSUE TITLE
推理速度：3090 24G FPS 只有5~6（'pretrained/SMPLer_h36m.pt'）

### ISSUE THREAD

**Issue by yx2009** [xuxy09/SMPLer#5]
注意到论文中提到的“ the inference of SMPLer and SMPLer-L runs at 96.0 and 73.9 frames per second (fps) respectively”。在Tesla M40上要达到96FPS，是不是经过其他方式对代码做过优化？或者是预训练模型与论文提到的模型不一样？

**Comment by xuxy09** [comment]
I haven’t tested on 3090 GPUs. I’m not sure about the cause of your suboptimal performance. Please ensure that your inference code is wrapped in a torch.no_grad context with a larger batch size.

**Comment by yx2009** [comment]
> I haven’t tested on 3090 GPUs. I’m not sure about the cause of your suboptimal performance. Please ensure that your inference code is wrapped in a torch.no_grad context with a larger batch size.

Wrapped the code as I can. That do nothing. It may be caused by the GPU or Windows OS. Still a good work.
